### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by aknyzsd** [ChenXu233/nonebot_plugin_dialectlist#21]
貌似在首次安装后可以使用，第二次启动bot后出现cannot import name threadlocalmetadata form sqlalchemy报错，是什么原因呢
03-16 23:53:23 [ERROR] nonebot | Failed to import "nonebot_plugin_dialectlist"
Traceback (most recent call last):
  File "C:\Users\n2006\Desktop\bot\Pallas-Bot\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\n2006\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dialectlist\__init__.py", line 26, in <module>
    from .function import get_message_records,msg_counter, msg_list2msg
  File "C:\Users\n2006\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dialectlist\function.py", line 5, in <module>
    from sqlmodel import select, or_
  File "C:\Program Files\Python39\lib\site-packages\sqlmodel\__init__.py", line 24, in <module>
    from sqlalchemy.schema import ThreadLocalMetaData as ThreadLocalMetaData
ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema' (C:\Program Files\Python39\lib\site-packages\sqlalchemy\schema.py)
![image](https://user-images.githubusercontent.com/121467598/225679385-2d4e1c87-d36b-41c1-981f-85c76e2f6f0e.png)

**Comment by ChenXu233** [comment]
是本插件的前置插件chatrecorder更新了,以前都是按照sqlite来的,现在不太一样,我现在来适配新的chatrecorder

**Comment by ChenXu233** [comment]
现在已经修复过了,你试试还能不能用

**Comment by aknyzsd** [comment]
可以了，谢谢大佬
