### ISSUE TITLE
AlconnaMatcher抛出AttributeError: 'UserInfo' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by YRRLYB** [ChenXu233/nonebot_plugin_dialectlist#36]
```cmd
09-19 19:41:44 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message  from @[群:] '/今日B话榜'
09-19 19:41:44 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_dialectlist, lineno=88)
DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000023AEDA3FD90>
DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000023AEDA3FD90> completed
DEBUG:aiosqlite:executing functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82C40>, 'regexp', 2, <function SQLiteDialect_pysqlite.on_connect.<locals>.regexp at 0x0000023AE6C915A0>, deterministic=True)
DEBUG:aiosqlite:operation functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82C40>, 'regexp', 2, <function SQLiteDialect_pysqlite.on_connect.<locals>.regexp at 0x0000023AE6C915A0>, deterministic=True) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82C40>, 'floor', 1, <built-in function floor>, deterministic=True)
DEBUG:aiosqlite:operation functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82C40>, 'floor', 1, <built-in function floor>, deterministic=True) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method cursor of sqlite3.Connection object at 0x0000023AE6C82C40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method cursor of sqlite3.Connection object at 0x0000023AE6C82C40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Cursor object at 0x0000023AE6CDB140>, 'SELECT nonebot_plugin_chatrecorder_messagerecord.id, nonebot_plugin_chatrecorder_messagerecord.session_persist_id, nonebot_plugin_chatrecorder_messagerecord.time, nonebot_plugin_chatrecorder_messagerecord.type, nonebot_plugin_chatrecorder_messagerecord.message_id, nonebot_plugin_chatrecorder_messagerecord.message, nonebot_plugin_chatrecorder_messagerecord.plain_text \nFROM nonebot_plugin_chatrecorder_messagerecord JOIN nonebot_plugin_session_orm_sessionmodel ON nonebot_plugin_session_orm_sessionmodel.id = nonebot_plugin_chatrecorder_messagerecord.session_persist_id \nWHERE nonebot_plugin_session_orm_sessionmodel.id2 = ? AND nonebot_plugin_chatrecorder_messagerecord.time >= ? AND nonebot_plugin_chatrecorder_messagerecord.time <= ? AND nonebot_plugin_chatrecorder_messagerecord.type = ?', ('655637792', '2024-09-18 16:00:00.000000', '2024-09-19 11:41:44.275840', 'message'))
DEBUG:aiosqlite:operation functools.partial(<built-in method execute of sqlite3.Cursor object at 0x0000023AE6CDB140>, 'SELECT nonebot_plugin_chatrecorder_messagerecord.id, nonebot_plugin_chatrecorder_messagerecord.session_persist_id, nonebot_plugin_chatrecorder_messagerecord.time, nonebot_plugin_chatrecorder_messagerecord.type, nonebot_plugin_chatrecorder_messagerecord.message_id, nonebot_plugin_chatrecorder_messagerecord.message, nonebot_plugin_chatrecorder_messagerecord.plain_text \nFROM nonebot_plugin_chatrecorder_messagerecord JOIN nonebot_plugin_session_orm_sessionmodel ON nonebot_plugin_session_orm_sessionmodel.id = nonebot_plugin_chatrecorder_messagerecord.session_persist_id \nWHERE nonebot_plugin_session_orm_sessionmodel.id2 = ? AND nonebot_plugin_chatrecorder_messagerecord.time >= ? AND nonebot_plugin_chatrecorder_messagerecord.time <= ? AND nonebot_plugin_chatrecorder_messagerecord.type = ?', ('655637792', '2024-09-18 16:00:00.000000', '2024-09-19 11:41:44.275840', 'message')) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method fetchall of sqlite3.Cursor object at 0x0000023AE6CDB140>)
DEBUG:aiosqlite:operation functools.partial(<built-in method fetchall of sqlite3.Cursor object at 0x0000023AE6CDB140>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x0000023AE6CDB140>)
DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x0000023AE6CDB140>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82C40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82C40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82C40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82C40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x0000023AE6C82C40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x0000023AE6C82C40>) completed
09-19 19:41:44 [INFO] nonebot_plugin_dialectlist | wow , there are 39 msgs to count !!!
09-19 19:41:44 [ERROR] nonebot_plugin_dialectlist | 群内拥有聊天记录的人数不足，无法获取到长度为5的排行榜,已将长度变化为：3
DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000023AEDA3DBD0>
DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000023AEDA3DBD0> completed
DEBUG:aiosqlite:executing functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82B40>, 'regexp', 2, <function SQLiteDialect_pysqlite.on_connect.<locals>.regexp at 0x0000023AE6C915A0>, deterministic=True)
DEBUG:aiosqlite:operation functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82B40>, 'regexp', 2, <function SQLiteDialect_pysqlite.on_connect.<locals>.regexp at 0x0000023AE6C915A0>, deterministic=True) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82B40>, 'floor', 1, <built-in function floor>, deterministic=True)
DEBUG:aiosqlite:operation functools.partial(<built-in method create_function of sqlite3.Connection object at 0x0000023AE6C82B40>, 'floor', 1, <built-in function floor>, deterministic=True) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method cursor of sqlite3.Connection object at 0x0000023AE6C82B40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method cursor of sqlite3.Connection object at 0x0000023AE6C82B40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Cursor object at 0x0000023AED5DCBC0>, 'SELECT nonebot_plugin_session_orm_sessionmodel.id, nonebot_plugin_session_orm_sessionmodel.bot_id, nonebot_plugin_session_orm_sessionmodel.bot_type, nonebot_plugin_session_orm_sessionmodel.platform, nonebot_plugin_session_orm_sessionmodel.level, nonebot_plugin_session_orm_sessionmodel.id1, nonebot_plugin_session_orm_sessionmodel.id2, nonebot_plugin_session_orm_sessionmodel.id3 \nFROM nonebot_plugin_session_orm_sessionmodel \nWHERE nonebot_plugin_session_orm_sessionmodel.id = ? OR nonebot_plugin_session_orm_sessionmodel.id = ? OR nonebot_plugin_session_orm_sessionmodel.id = ?', (4, 275, 1038))
DEBUG:aiosqlite:operation functools.partial(<built-in method execute of sqlite3.Cursor object at 0x0000023AED5DCBC0>, 'SELECT nonebot_plugin_session_orm_sessionmodel.id, nonebot_plugin_session_orm_sessionmodel.bot_id, nonebot_plugin_session_orm_sessionmodel.bot_type, nonebot_plugin_session_orm_sessionmodel.platform, nonebot_plugin_session_orm_sessionmodel.level, nonebot_plugin_session_orm_sessionmodel.id1, nonebot_plugin_session_orm_sessionmodel.id2, nonebot_plugin_session_orm_sessionmodel.id3 \nFROM nonebot_plugin_session_orm_sessionmodel \nWHERE nonebot_plugin_session_orm_sessionmodel.id = ? OR nonebot_plugin_session_orm_sessionmodel.id = ? OR nonebot_plugin_session_orm_sessionmodel.id = ?', (4, 275, 1038)) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method fetchall of sqlite3.Cursor object at 0x0000023AED5DCBC0>)
DEBUG:aiosqlite:operation functools.partial(<built-in method fetchall of sqlite3.Cursor object at 0x0000023AED5DCBC0>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x0000023AED5DCBC0>)
DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x0000023AED5DCBC0>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82B40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82B40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82B40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method rollback of sqlite3.Connection object at 0x0000023AE6C82B40>) completed
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x0000023AE6C82B40>)
DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x0000023AE6C82B40>) completed
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='D:\\bot\\llonebot\\nonebot\\buding\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='D:\\bot\\llonebot\\nonebot\\buding\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='D:\\bot\\llonebot\\nonebot\\buding\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=7890 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x0000023AEDAD5180>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Connection', b'close'), (b'Content-Length', b'66606'), (b'Cache-Control', b'max-age=2592000'), (b'Chid', b'0'), (b'Content-Type', b'image/jpeg'), (b'Fid', b'0'), (b'Last-Modified', b'Sat, 07 Sep 2024 02:32:34 GMT'), (b'Server', b'ImgHttp3.0.0'), (b'Size', b'66606'), (b'User-Returncode', b'0'), (b'Vary', b'Accept,Origin'), (b'X-Bcheck', b'1725676354_0'), (b'X-Cpt', b'filename=0'), (b'X-Datasrc', b'9'), (b'X-Delay', b'41427 us'), (b'X-Info', b'real data'), (b'X-Region', b'nj'), (b'X-Reqgue', b'0')])
INFO:httpx:HTTP Request: GET http://q1.qlogo.cn/g?b=qq&nk=3254276970&s=640 "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
09-19 19:41:45 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_dialectlist, lineno=88) running complete
09-19 19:41:45 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_dialectlist, lineno=88) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\bot\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\bot\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\bot\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\bot\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\bot\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\bot\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot_plugin_dialectlist\__init__.py", line 243, in handle_rank
    user = UserRankInfo(**user_info.model_dump(),
AttributeError: 'UserInfo' object has no attribute 'model_dump'
```
救救qwq

**Comment by ChenXu233** [comment]
你python是那个版本，还有插件是那个版本的，nonebot的版本，能具体提供一下你的环境吗？

**Comment by ChenXu233** [comment]
我猜是你的插件版本太低了，升级一下试试（

**Comment by YRRLYB** [comment]
好的，我的py版本是3.10.11 nonebot版本也是最新的2.3.3 插件是使用的2.2.4

**Comment by YRRLYB** [comment]
哦不对，是2.3.0

**Comment by YRRLYB** [comment]
……用了你的新的版本就可以使用了，非常感谢！（
